/**
 * StreamingBus — lightweight SSE fan-out for streaming overlays.
 *
 * Streamers connect a browser-source in OBS to:
 *   GET /api/stream/:gameId/overlay
 *
 * The bus receives periodic game-state snapshots pushed by the Worker
 * (sourced from SpectatorBus message decoding or NarratorBus activity)
 * and fans them out as SSE events.
 *
 * Architecture: pull from NarratorBus activity + periodic heartbeat.
 * No game simulation — just event relay.
 */

import type { Response } from "express";
import { BoundedSseTransport, type SseAdmission } from "./BoundedSseTransport";
import { logger as Logger } from "./Logger";

export interface StreamSnapshot {
  gameId: string;
  tick?: number;
  commentary?: string;
  activity?: string;
  playerCount?: number;
  mapName?: string;
}

interface StreamState {
  clients: Set<Response>;
  lastSnapshot: StreamSnapshot | null;
  recentEvents: object[];
  timer: ReturnType<typeof setInterval> | null;
}

const HEARTBEAT_MS = 5_000;
const MAX_RECENT_EVENTS = 12;
export const STREAMING_SSE_POLICY = {
  maxSubscribersPerGame: 32,
  maxSubscribersPerWorker: 256,
  maxSubscribersPerIp: 8,
  maxQueuedEventsPerClient: 24,
  maxQueuedBytesPerClient: 64 * 1024,
  drainTimeoutMs: 5_000,
} as const;

export class StreamingBus {
  private streams = new Map<string, StreamState>();
  private readonly transport = new BoundedSseTransport(STREAMING_SSE_POLICY);

  private getOrCreate(gameId: string): StreamState {
    if (!this.streams.has(gameId)) {
      const state: StreamState = {
        clients: new Set(),
        lastSnapshot: null,
        recentEvents: [],
        timer: null,
      };
      state.timer = setInterval(() => this.heartbeat(gameId), HEARTBEAT_MS);
      state.timer.unref?.();
      this.streams.set(gameId, state);
    }
    return this.streams.get(gameId)!;
  }

  admit(gameId: string, clientKey: string): SseAdmission {
    return this.transport.admit(gameId, clientKey);
  }

  subscribe(gameId: string, res: Response, clientKey: string): SseAdmission {
    const state = this.getOrCreate(gameId);
    const admission = this.transport.subscribe(gameId, clientKey, res, () => {
      state.clients.delete(res);
      if (state.clients.size === 0) this.cleanup(gameId);
    });
    if (!admission.accepted) {
      if (state.clients.size === 0) this.cleanup(gameId);
      return admission;
    }
    state.clients.add(res);

    this.transport.write(
      res,
      `data: ${JSON.stringify({ type: "connected", gameId })}\n\n`,
    );

    // Send last snapshot immediately if available
    if (state.lastSnapshot) {
      this.transport.write(
        res,
        `data: ${JSON.stringify({ type: "snapshot", ...state.lastSnapshot })}\n\n`,
      );
    }
    for (const event of state.recentEvents) {
      this.transport.write(
        res,
        `data: ${JSON.stringify({ type: "replay", event })}\n\n`,
      );
    }

    Logger.info(`StreamingBus: overlay client connected to ${gameId}`, {
      count: state.clients.size,
    });
    return admission;
  }

  /** Push a game-state snapshot to all overlay clients. */
  pushSnapshot(snapshot: StreamSnapshot): void {
    const state = this.streams.get(snapshot.gameId);
    if (!state || state.clients.size === 0) return;
    state.lastSnapshot = snapshot;
    this.broadcast(state, { type: "snapshot", ...snapshot });
  }

  /** Push commentary text generated by NarratorBus. */
  pushCommentary(gameId: string, text: string): void {
    const state = this.streams.get(gameId);
    if (!state || state.clients.size === 0) return;
    this.broadcast(state, { type: "commentary", gameId, text });
  }

  closeGame(gameId: string): void {
    const state = this.streams.get(gameId);
    if (!state) return;
    this.broadcast(state, { type: "game_over", gameId });
    this.transport.closeGame(gameId);
    this.cleanup(gameId);
  }

  private heartbeat(gameId: string): void {
    const state = this.streams.get(gameId);
    if (!state || state.clients.size === 0) return;
    this.broadcast(state, { type: "heartbeat", gameId, ts: Date.now() });
  }

  private broadcast(state: StreamState, payload: object): void {
    this.remember(state, payload);
    const line = `data: ${JSON.stringify(payload)}\n\n`;
    for (const res of state.clients) {
      this.transport.write(res, line);
    }
  }

  private remember(state: StreamState, payload: object): void {
    const type = (payload as { type?: string }).type;
    if (type === "heartbeat" || type === "connected" || type === "replay") {
      return;
    }
    state.recentEvents.push(payload);
    if (state.recentEvents.length > MAX_RECENT_EVENTS) {
      state.recentEvents.splice(
        0,
        state.recentEvents.length - MAX_RECENT_EVENTS,
      );
    }
  }

  private cleanup(gameId: string): void {
    const state = this.streams.get(gameId);
    if (state?.timer) clearInterval(state.timer);
    this.streams.delete(gameId);
  }

  hasSubscribers(gameId: string): boolean {
    return (this.streams.get(gameId)?.clients.size ?? 0) > 0;
  }

  debugState(gameId: string): { subscribers: number; recentEvents: number } {
    const state = this.streams.get(gameId);
    return {
      subscribers: state?.clients.size ?? 0,
      recentEvents: state?.recentEvents.length ?? 0,
    };
  }

  integritySnapshot() {
    return this.transport.snapshot();
  }
}

export const streamingBus = new StreamingBus();
