#!/usr/bin/env bash
# Remote immutable container updater with bounded cleanup and health rollback.
set -euo pipefail

if [[ $# -ne 1 || ! -f "$1" ]]; then
    echo "Usage: $0 <environment-file>" >&2
    exit 2
fi
ENV_FILE="$1"
# shellcheck disable=SC1090 -- file is generated by deploy.sh using printf %q
source "$ENV_FILE"

: "${GHCR_IMAGE:?GHCR_IMAGE is required}"
: "${GHCR_USERNAME:?GHCR_USERNAME is required}"
: "${GHCR_TOKEN:?GHCR_TOKEN is required for the remote registry pull}"
: "${DEPLOY_HEALTH_URL:?DEPLOY_HEALTH_URL is required}"
: "${DEPLOY_INGRESS_PORT:?DEPLOY_INGRESS_PORT is required from the CANON-038 allocation}"
[[ "$GHCR_IMAGE" =~ @sha256:[0-9a-f]{64}$ ]] || {
    echo "Remote update rejected a mutable image reference" >&2
    exit 2
}
IMAGE_DIGEST="${GHCR_IMAGE##*@}"
[[ "$DEPLOY_INGRESS_PORT" =~ ^[0-9]+$ ]] \
    && ((DEPLOY_INGRESS_PORT >= 8110 && DEPLOY_INGRESS_PORT <= 8999)) || {
    echo "DEPLOY_INGRESS_PORT must be an allocated CANON-038 port in 8110-8999" >&2
    exit 2
}

APP_NAME="${APP_NAME:-vaultfront}"
for identifier in "$APP_NAME" "$ENV" "$SUBDOMAIN"; do
    [[ "$identifier" =~ ^[a-z0-9-]+$ ]] || {
        echo "Deployment identifiers must contain only lowercase letters, digits, and hyphens" >&2
        exit 2
    }
done
DEPLOYMENT_KEY="${APP_NAME}-${ENV}-${SUBDOMAIN}"
NETWORK_NAME="${DEPLOYMENT_KEY}-private"
ROUTER_NAME="${DEPLOYMENT_KEY}-router"
ROUTER_STATE_DIR="${HOME}/.${APP_NAME}/${DEPLOYMENT_KEY}"
ROUTER_CONFIG="${ROUTER_STATE_DIR}/router.conf"
EVIDENCE_STATE_DIR="${ROUTER_STATE_DIR}/release-evidence"
[[ "$ROUTER_STATE_DIR" == "$HOME/.$APP_NAME/$DEPLOYMENT_KEY" ]] || {
    echo "Router state escaped the project-owned directory" >&2
    exit 2
}
mkdir -p "$EVIDENCE_STATE_DIR"
# The bundle contains signed public observations, never signing material. The
# container's non-root node UID differs from the project host UID, so the
# read-only bind mount must remain traversable across that boundary.
chmod 755 "$EVIDENCE_STATE_DIR"
IMAGE_REPO="${GHCR_IMAGE%@sha256:*}"
RETENTION="${DEPLOY_IMAGE_RETENTION:-5}"
DEPLOY_DRAIN_TIMEOUT_SECONDS="${DEPLOY_DRAIN_TIMEOUT_SECONDS:-900}"
[[ "$DEPLOY_DRAIN_TIMEOUT_SECONDS" =~ ^[0-9]+$ ]] \
    && ((DEPLOY_DRAIN_TIMEOUT_SECONDS >= 45 && DEPLOY_DRAIN_TIMEOUT_SECONDS <= 10800)) || {
    echo "DEPLOY_DRAIN_TIMEOUT_SECONDS must be between 45 and 10800" >&2
    exit 2
}
RESTART=no
if [[ "${DEPLOY_ALWAYS_RESTART:-}" == "true" || "$SUBDOMAIN" == "main" || "$ENV" == "prod" ]]; then
    RESTART=always
fi

# Authenticate the isolated deploy user without persisting registry credentials.
# The app receives a sanitized environment file so deployment-plane credentials
# can never leak into either the schema migration or the long-lived container.
DOCKER_AUTH_DIR="$(mktemp -d)"
RUNTIME_ENV_FILE="$(mktemp)"
cleanup() {
    rm -f "$ENV_FILE" "$RUNTIME_ENV_FILE"
    rm -rf "$DOCKER_AUTH_DIR"
}
trap cleanup EXIT

# deploy.sh emits a shell-safe transport file because this updater must source
# it. Docker's --env-file format does not interpret shell quoting, so serialize
# the sourced values again instead of forwarding expressions such as FOO=''.
# Reject multiline values because Docker env files are line-oriented.
: > "$RUNTIME_ENV_FILE"
while IFS='=' read -r variable _; do
    [[ "$variable" =~ ^[A-Z_][A-Z0-9_]*$ ]] || {
        echo "Generated environment contains an invalid variable name" >&2
        exit 2
    }
    case "$variable" in
        GHCR_TOKEN | CF_API_TOKEN) continue ;;
    esac
    runtime_value="${!variable-}"
    if [[ "$runtime_value" == *$'\n'* || "$runtime_value" == *$'\r'* ]]; then
        echo "Runtime environment values must be single-line" >&2
        exit 2
    fi
    printf '%s=%s\n' "$variable" "$runtime_value" >> "$RUNTIME_ENV_FILE"
done < "$ENV_FILE"
chmod 600 "$RUNTIME_ENV_FILE"
export DOCKER_CONFIG="$DOCKER_AUTH_DIR"
printf '%s' "$GHCR_TOKEN" | docker login ghcr.io \
    --username "$GHCR_USERNAME" \
    --password-stdin > /dev/null

docker pull "$GHCR_IMAGE"
docker image inspect "$GHCR_IMAGE" > /dev/null
: "${DATABASE_URL:?DATABASE_URL is required for release migration}"
docker network create "$NETWORK_NAME" > /dev/null 2>&1 || true
DATABASE_DOCKER_CONTAINER="${DATABASE_DOCKER_CONTAINER:-}"
if [[ -n "$DATABASE_DOCKER_CONTAINER" ]]; then
    [[ "$DATABASE_DOCKER_CONTAINER" =~ ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$ ]] || {
        echo "DATABASE_DOCKER_CONTAINER has an invalid Docker identifier" >&2
        exit 2
    }
    docker network connect "$NETWORK_NAME" "$DATABASE_DOCKER_CONTAINER" > /dev/null 2>&1 || {
        docker inspect \
            --format '{{json .NetworkSettings.Networks}}' \
            "$DATABASE_DOCKER_CONTAINER" | grep -q "\\\"${NETWORK_NAME}\\\"" || {
            echo "Database container could not join the project-private network" >&2
            exit 1
        }
    }
fi
docker run --rm \
    --network "$NETWORK_NAME" \
    --env-file "$RUNTIME_ENV_FILE" \
    --entrypoint node \
    "$GHCR_IMAGE" \
    --import tsx src/server/db/apply-schema.ts

# Resolve the incumbent without trusting a mutable tag. Older deployments used
# DEPLOYMENT_KEY as the container name and did not carry generation labels, so
# keep one bounded compatibility lookup for the first blue/green handoff.
mapfile -t INCUMBENTS < <(
    docker ps \
        --filter "label=com.vaultfront.deployment=${DEPLOYMENT_KEY}" \
        --filter "label=com.vaultfront.role=app" \
        --format '{{.Names}}'
)
if ((${#INCUMBENTS[@]} > 1)); then
    echo "Refusing promotion: multiple active incumbents found for ${DEPLOYMENT_KEY}" >&2
    exit 1
fi
OLD_CONTAINER="${INCUMBENTS[0]:-}"
if [[ -z "$OLD_CONTAINER" ]] && docker container inspect "$DEPLOYMENT_KEY" > /dev/null 2>&1; then
    OLD_CONTAINER="$DEPLOYMENT_KEY"
fi
OLD_IMAGE=""
OLD_GENERATION=0
if [[ -n "$OLD_CONTAINER" ]]; then
    OLD_IMAGE="$(docker inspect --format '{{.Config.Image}}' "$OLD_CONTAINER")"
    OLD_GENERATION="$(
        docker inspect \
            --format '{{ index .Config.Labels "com.vaultfront.generation" }}' \
            "$OLD_CONTAINER" 2> /dev/null || true
    )"
    [[ "$OLD_GENERATION" =~ ^[0-9]+$ ]] || OLD_GENERATION=0
fi
NEW_GENERATION=$((OLD_GENERATION + 1))
DIGEST_SHORT="${IMAGE_DIGEST#sha256:}"
DIGEST_SHORT="${DIGEST_SHORT:0:12}"
CONTAINER_NAME="${DEPLOYMENT_KEY}-g${NEW_GENERATION}-${DIGEST_SHORT}"

run_container() {
    local image="$1"
    local name="$2"
    local generation="$3"
    docker run -d \
        --restart="$RESTART" \
        --env-file "$RUNTIME_ENV_FILE" \
        --name "$name" \
        --network "$NETWORK_NAME" \
        --volume "${EVIDENCE_STATE_DIR}:/run/vaultfront-release-evidence:ro" \
        --label "com.vaultfront.deployment=${DEPLOYMENT_KEY}" \
        --label "com.vaultfront.role=app" \
        --label "com.vaultfront.generation=${generation}" \
        --label "com.vaultfront.image-digest=${IMAGE_DIGEST}" \
        "$image"
}

dump_candidate_diagnostics() {
    echo "Candidate diagnostics for ${CONTAINER_NAME}:" >&2
    docker exec "$CONTAINER_NAME" supervisorctl status >&2 || true
    docker logs --tail 200 "$CONTAINER_NAME" >&2 || true
}

# Start and prove the candidate before signalling the incumbent. The higher
# project-router route is activated only after health and immutable revision
# checks; shared Caddy always targets the one allocated loopback port.
run_container "$GHCR_IMAGE" "$CONTAINER_NAME" "$NEW_GENERATION"
CANDIDATE_HEALTHY=0
for _ in {1..30}; do
    if docker exec "$CONTAINER_NAME" curl -fsS --max-time 5 http://127.0.0.1/_health > /dev/null; then
        CANDIDATE_HEALTHY=1
        break
    fi
    sleep 2
done
if [[ "$CANDIDATE_HEALTHY" != "1" ]]; then
    echo "Candidate health verification failed; incumbent remains active" >&2
    dump_candidate_diagnostics
    docker stop --time 45 "$CONTAINER_NAME" > /dev/null 2>&1 || true
    docker rm "$CONTAINER_NAME" > /dev/null 2>&1 || true
    exit 1
fi

# Docker health is the candidate-local admission signal. Wait for it before
# changing the stable project router, so the incumbent remains untouched.
DOCKER_HEALTHY=0
for _ in {1..90}; do
    if [[ "$(docker inspect --format '{{.State.Health.Status}}' "$CONTAINER_NAME")" == "healthy" ]]; then
        DOCKER_HEALTHY=1
        break
    fi
    sleep 2
done
if [[ "$DOCKER_HEALTHY" != "1" ]]; then
    echo "Candidate never reached Docker healthy state; incumbent remains active" >&2
    dump_candidate_diagnostics
    docker stop --time 45 "$CONTAINER_NAME" > /dev/null 2>&1 || true
    docker rm "$CONTAINER_NAME" > /dev/null 2>&1 || true
    exit 1
fi

EXPECTED_REVISION="$(
    docker inspect \
        --format '{{ index .Config.Labels "org.opencontainers.image.revision" }}' \
        "$CONTAINER_NAME"
)"
REVISION_URL="${DEPLOY_HEALTH_URL%/_health}/commit.txt"
if [[ -z "$EXPECTED_REVISION" || "$EXPECTED_REVISION" == "unknown" ]]; then
    echo "Candidate has no immutable Git revision; incumbent remains active" >&2
    dump_candidate_diagnostics
    docker stop --time 45 "$CONTAINER_NAME" > /dev/null 2>&1 || true
    docker rm "$CONTAINER_NAME" > /dev/null 2>&1 || true
    exit 1
fi

write_router_config() {
    local target="$1"
    local output="$2"
    [[ "$target" =~ ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$ ]] || {
        echo "Invalid router target" >&2
        return 2
    }
    cat > "$output" << EOF
map \$http_upgrade \$connection_upgrade {
    default upgrade;
    '' close;
}
resolver 127.0.0.11 valid=5s ipv6=off;
server {
    listen 80;
    location / {
        set \$vaultfront_backend ${target};
        proxy_pass http://\$vaultfront_backend:80;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_read_timeout 10800s;
        proxy_send_timeout 10800s;
    }
}
EOF
}

activate_route() {
    local target="$1"
    local validation_image="$2"
    local candidate_dir="${ROUTER_STATE_DIR}/candidate"
    local candidate_config="${candidate_dir}/router.conf"
    mkdir -p "$ROUTER_STATE_DIR" || return 1
    rm -rf "$candidate_dir" || return 1
    mkdir -p "$candidate_dir" || return 1
    write_router_config "$target" "$candidate_config" || {
        rm -rf "$candidate_dir"
        return 1
    }
    docker run --rm \
        --network "$NETWORK_NAME" \
        --volume "${candidate_dir}:/etc/nginx/conf.d:ro" \
        --entrypoint nginx \
        "$validation_image" -t || {
        rm -rf "$candidate_dir"
        return 1
    }
    cp "$candidate_config" "$ROUTER_CONFIG" || {
        rm -rf "$candidate_dir"
        return 1
    }
    if docker container inspect "$ROUTER_NAME" > /dev/null 2>&1; then
        local router_bind
        router_bind="$(docker port "$ROUTER_NAME" 80/tcp | head -n 1)"
        [[ "$router_bind" == "127.0.0.1:${DEPLOY_INGRESS_PORT}" ]] || {
            echo "Project router bind ${router_bind:-missing} does not match allocated 127.0.0.1:${DEPLOY_INGRESS_PORT}" >&2
            rm -rf "$candidate_dir"
            return 1
        }
        docker exec "$ROUTER_NAME" nginx -t || {
            rm -rf "$candidate_dir"
            return 1
        }
        docker exec "$ROUTER_NAME" nginx -s reload || {
            rm -rf "$candidate_dir"
            return 1
        }
    else
        docker run -d \
            --restart=always \
            --name "$ROUTER_NAME" \
            --network "$NETWORK_NAME" \
            --publish "127.0.0.1:${DEPLOY_INGRESS_PORT}:80" \
            --volume "${ROUTER_STATE_DIR}:/etc/nginx/conf.d:ro" \
            --label "com.vaultfront.deployment=${DEPLOYMENT_KEY}" \
            --label "com.vaultfront.role=router" \
            --entrypoint nginx \
            "$validation_image" -g 'daemon off;' || {
            rm -rf "$candidate_dir"
            return 1
        }
    fi
    rm -rf "$candidate_dir"
}

restore_incumbent_route() {
    if [[ -n "$OLD_CONTAINER" && -n "$OLD_IMAGE" ]]; then
        docker start "$OLD_CONTAINER" > /dev/null 2>&1 || true
        activate_route "$OLD_CONTAINER" "$OLD_IMAGE"
    else
        docker stop --time 45 "$ROUTER_NAME" > /dev/null 2>&1 || true
        docker rm "$ROUTER_NAME" > /dev/null 2>&1 || true
        rm -f "$ROUTER_CONFIG"
    fi
}

# Switch only the project-private router. Caddy remains the sole shared-host
# public ingress authority and forwards to 127.0.0.1:DEPLOY_INGRESS_PORT.
if ! activate_route "$CONTAINER_NAME" "$GHCR_IMAGE"; then
    echo "Candidate route activation failed; restoring the incumbent route" >&2
    dump_candidate_diagnostics
    restore_incumbent_route || true
    docker stop --time 45 "$CONTAINER_NAME" > /dev/null 2>&1 || true
    docker rm "$CONTAINER_NAME" > /dev/null 2>&1 || true
    exit 1
fi

ROUTER_ADMITTED=0
for _ in {1..30}; do
    if [[ "$(curl -fsS --max-time 5 "http://127.0.0.1:${DEPLOY_INGRESS_PORT}/commit.txt" 2> /dev/null || true)" == "$EXPECTED_REVISION" ]]; then
        ROUTER_ADMITTED=1
        break
    fi
    sleep 2
done
if [[ "$ROUTER_ADMITTED" != "1" ]]; then
    echo "Candidate revision was not admitted through the project router; incumbent remains active" >&2
    restore_incumbent_route
    docker stop --time 45 "$CONTAINER_NAME" > /dev/null 2>&1 || true
    docker rm "$CONTAINER_NAME" > /dev/null 2>&1 || true
    exit 1
fi

CANDIDATE_ADMITTED=0
for _ in {1..30}; do
    if [[ "$(curl -fsS --max-time 5 "$REVISION_URL" 2> /dev/null || true)" == "$EXPECTED_REVISION" ]]; then
        CANDIDATE_ADMITTED=1
        break
    fi
    sleep 2
done
if [[ "$CANDIDATE_ADMITTED" != "1" ]]; then
    echo "Candidate revision was not admitted through shared Caddy ingress; incumbent remains active" >&2
    restore_incumbent_route
    docker stop --time 45 "$CONTAINER_NAME" > /dev/null 2>&1 || true
    docker rm "$CONTAINER_NAME" > /dev/null 2>&1 || true
    exit 1
fi

if [[ -n "$OLD_CONTAINER" && "$OLD_CONTAINER" != "$CONTAINER_NAME" ]]; then
    echo "Draining incumbent ${OLD_CONTAINER} for up to ${DEPLOY_DRAIN_TIMEOUT_SECONDS}s."
    docker stop --time "$DEPLOY_DRAIN_TIMEOUT_SECONDS" "$OLD_CONTAINER"
fi

# Reverify health and immutable revision after the incumbent has drained. On
# failure, restore the exact old container and retire only the candidate.
LIVE_HEALTHY=0
for _ in {1..30}; do
    if curl -fsS --max-time 5 "$DEPLOY_HEALTH_URL" > /dev/null \
        && [[ "$(curl -fsS --max-time 5 "$REVISION_URL" 2> /dev/null || true)" == "$EXPECTED_REVISION" ]]; then
        LIVE_HEALTHY=1
        break
    fi
    sleep 2
done
if [[ "$LIVE_HEALTHY" != "1" ]]; then
    echo "Ingress health verification failed; restoring incumbent" >&2
    restore_incumbent_route
    docker stop --time 45 "$CONTAINER_NAME" > /dev/null 2>&1 || true
    docker rm "$CONTAINER_NAME" > /dev/null 2>&1 || true
    exit 1
fi

if [[ -n "$OLD_CONTAINER" && "$OLD_CONTAINER" != "$CONTAINER_NAME" ]]; then
    docker rm "$OLD_CONTAINER" > /dev/null
fi

# Keep the newest N unique images for this repository; never prune the host globally.
mapfile -t STALE_IMAGES < <(
    docker image ls "$IMAGE_REPO" --format '{{.ID}}' \
        | awk '!seen[$0]++' \
        | tail -n "+$((RETENTION + 1))"
)
for image_id in "${STALE_IMAGES[@]}"; do
    docker image rm "$image_id" > /dev/null 2>&1 || true
done
docker container prune --filter "until=168h" -f > /dev/null

echo "Remote update healthy for ${CONTAINER_NAME} at immutable digest ${GHCR_IMAGE##*@}; generation ${NEW_GENERATION} admitted after bounded incumbent drain."
