#!/usr/bin/env bash
# Remote immutable container updater with bounded cleanup and health rollback.
set -euo pipefail

if [[ $# -ne 1 || ! -f "$1" ]]; then
    echo "Usage: $0 <environment-file>" >&2
    exit 2
fi
ENV_FILE="$1"
trap 'rm -f "$ENV_FILE"' EXIT
# shellcheck disable=SC1090 -- file is generated by deploy.sh using printf %q
source "$ENV_FILE"

: "${GHCR_IMAGE:?GHCR_IMAGE is required}"
: "${DEPLOY_HEALTH_URL:?DEPLOY_HEALTH_URL is required}"
[[ "$GHCR_IMAGE" =~ @sha256:[0-9a-f]{64}$ ]] || {
    echo "Remote update rejected a mutable image reference" >&2
    exit 2
}

APP_NAME="${APP_NAME:-vaultfront}"
CONTAINER_NAME="${APP_NAME}-${ENV}-${SUBDOMAIN}"
IMAGE_REPO="${GHCR_IMAGE%@sha256:*}"
RETENTION="${DEPLOY_IMAGE_RETENTION:-5}"
RESTART=no
if [[ "${DEPLOY_ALWAYS_RESTART:-}" == "true" || "$SUBDOMAIN" == "main" || "$ENV" == "prod" ]]; then
    RESTART=always
fi

docker pull "$GHCR_IMAGE"
docker image inspect "$GHCR_IMAGE" > /dev/null
OLD_IMAGE="$(docker inspect --format '{{.Config.Image}}' "$CONTAINER_NAME" 2> /dev/null || true)"
if docker container inspect "$CONTAINER_NAME" > /dev/null 2>&1; then
    docker rm -f "$CONTAINER_NAME"
fi
docker network create web > /dev/null 2>&1 || true

run_container() {
    local image="$1"
    docker run -d \
        --restart="$RESTART" \
        --env-file "$ENV_FILE" \
        --name "$CONTAINER_NAME" \
        --network web \
        --label "traefik.enable=true" \
        --label "traefik.http.routers.${CONTAINER_NAME}.rule=Host(\`${SUBDOMAIN}.${DOMAIN}\`)" \
        --label "traefik.http.routers.${CONTAINER_NAME}.entrypoints=websecure" \
        --label "traefik.http.routers.${CONTAINER_NAME}.tls=true" \
        --label "traefik.http.services.${CONTAINER_NAME}.loadbalancer.server.port=80" \
        "$image"
}

run_container "$GHCR_IMAGE"
HEALTHY=0
for _ in {1..30}; do
    if curl -fsS --max-time 5 "$DEPLOY_HEALTH_URL" > /dev/null; then
        HEALTHY=1
        break
    fi
    sleep 2
done
if [[ "$HEALTHY" != "1" ]]; then
    echo "Health verification failed; rolling back the container" >&2
    docker rm -f "$CONTAINER_NAME" > /dev/null 2>&1 || true
    if [[ -n "$OLD_IMAGE" ]]; then run_container "$OLD_IMAGE"; fi
    exit 1
fi

# Keep the newest N unique images for this repository; never prune the host globally.
mapfile -t STALE_IMAGES < <(
    docker image ls "$IMAGE_REPO" --format '{{.ID}}' \
        | awk '!seen[$0]++' \
        | tail -n "+$((RETENTION + 1))"
)
for image_id in "${STALE_IMAGES[@]}"; do
    docker image rm "$image_id" > /dev/null 2>&1 || true
done
docker container prune --filter "until=168h" -f > /dev/null

echo "Remote update healthy for ${CONTAINER_NAME} at immutable digest ${GHCR_IMAGE##*@}."
